#!/usr/bin/env python

from datetime import datetime as dt
import argparse
import re

parser = argparse.ArgumentParser(description='Compute measurement time of NMR experiment.')
parser.add_argument('dir', nargs='?', default='.', help='Destination of experiment data.')

filename = parser.parse_args().dir + '/audita.txt'

pattern = r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}"
form = "%Y-%m-%d %H:%M:%S"

try:
    with open(filename, 'r') as f:
        str_end, str_start = re.findall(pattern, f.read())
except IOError:
    quit()

start = dt.strptime(str_start, form)
end = dt.strptime(str_end, form)

print end - start
